version: '3.8'
services:
  bot:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "8501:8501"
    command: >
      bash -c "pip install --no-cache-dir -r requirements.txt && \
               scripts/setup_env.sh && \
               uvicorn api.main:app --host 0.0.0.0 --port 8000 & \
               streamlit run dashboard/app.py --server.port 8501 --server.address 0.0.0.0"
    restart: always     # ← هذا السطر يضمن إعادة التشغيل تلقائيًا
    environment:
      - PYTHONUNBUFFERED=1
