services:
  bot:
    # ...
    ports:
      - "8000:8000"
    command: bash -c "\
      pip install --no-cache-dir -r requirements.txt && \
      scripts/setup_env.sh && \
      uvicorn api.main:app --host 0.0.0.0 --port 8000 \
    "
